# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evicted_frontend", "0002_add_vehicle_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="EVLot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("carplate", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("time_parked", models.DateTimeField(help_text="When the car was parked")),
                ("time_left", models.DateTimeField(blank=True, help_text="When the car left (null if still parked)", null=True)),
                ("phone", models.CharField(max_length=20)),
                ("lot_number", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "EV Lot",
                "verbose_name_plural": "EV Lots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("carplate", models.CharField(max_length=20)),
                ("type", models.CharField(choices=[("ICE", "ICE"), ("EV", "EV")], max_length=10)),
                ("time_entered", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
                "ordering": ["-time_entered"],
            },
        ),
    ]
