# Generated by Django 5.2.12 on 2026-03-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carplate', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('time_parked', models.DateTimeField(help_text='Set when staff triggers workflow')),
                ('time_car_left', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('lot_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('lot_number', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
