# Generated by Django 5.2.12 on 2026-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evicted', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carplate', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('ICE', 'ICE'), ('EV', 'EV')], max_length=10)),
                ('time_entered', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Vehicle entries',
                'ordering': ['-time_entered'],
            },
        ),
    ]
