# Generated by Django 6.0.3 on 2026-03-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evicted', '0005_add_parkinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='time_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
